/**
 * On-device motion library loader (mirrors model/src/synthesis/motion.py).
 *
 * Loads the bundled motionLibrary.json (generated by scripts/sync_app_assets.py)
 * and exposes per-gloss (T, 42, 3) landmark motion templates as flat arrays.
 */

import motionLibrary from './motionLibrary.json';

export interface MotionLibraryJson {
  frames: number;
  version: string;
  motions: Record<string, number[]>;
}

const DATA = motionLibrary as unknown as MotionLibraryJson;

export const MOTION_FRAMES = DATA.frames;
export const V = 42;
export const C = 3;

export class MotionLibrary {
  private motions: Record<string, number[]>;
  frames: number;

  constructor(data: MotionLibraryJson) {
    this.motions = data.motions;
    this.frames = data.frames;
  }

  has(gloss: string): boolean {
    return gloss in this.motions;
  }

  /** Return the (T, V, C) motion template for a gloss as a flat Float32Array. */
  get(gloss: string): Float32Array {
    const raw = this.motions[gloss];
    if (!raw) return new Float32Array(this.frames * V * C);
    return Float32Array.from(raw);
  }
}

export function createMotionLibrary(): MotionLibrary {
  return new MotionLibrary(DATA);
}
